### ISSUE TITLE
Babel plugin should add React import if necessary

### ISSUE THREAD

**Issue by jaydenseric** [vercel/styled-jsx#575]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What is the current behavior?

The `styled-jsx/babel` Babel plugin adds JSX code when transforming use of `css.resolve` from `styled-jsx/css`, assuming `React` is in the module scope. In reality, this is sometimes not the case.

I am building a UI library with seperate files for each shared style, and figured out the hard way that you must manually import `React` like this:

```js
// eslint-disable-next-line no-unused-vars
import React from 'react'
import css from 'styled-jsx/css'
```

This is a gotcha, because the source code doesn't contain any JSX, and having to disable the ESLint `no-unused-vars` rule is pretty gross.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

In `foo.js`, add:

```js
import css from 'styled-jsx/css'

export const styles = css.resolve`
  a {
    color: red;
  }
`
```

Then transpile it with Babel using the `styled-jsx/babel` plugin and the `@babel/preset-react` preset.

The result is:

```js
import _JSXStyle from "styled-jsx/style";
export const styles = {
  styles: React.createElement(
    _JSXStyle,
    {
      id: "863786060"
    },
    "a.jsx-863786060{color:red;}"
  ),
  className: "jsx-863786060"
};
```

Note that an import for `React` has not been added to the module, which will result in a runtime error.

#### What is the expected behavior?

The `styled-jsx/babel` Babel plugin should add any imports necessary to support the code it adds; specifically it needs to import `React`.

#### Environment (include versions)

* OS: N/A
* Browser: N/A
* styled-jsx (version): v3.2.1

#### Did this work in previous versions?

Don't know, probably not.

**Comment by giuseppeg** [comment]
yup makes sense @jaydenseric would you try to give this a stab?

**Comment by huozhi** [comment]
With [react jsx transform in automatic runtime](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) we don't need to manually add import of react to the source code
