### ISSUE TITLE
Bug: Tests still render jsx-123 classNames

### ISSUE THREAD

**Issue by etiennejcharles** [vercel/styled-jsx#649]
**Given** I install the jest example https://github.com/vercel/next.js/tree/canary/examples/with-jest
**And** have the described .babelrc configuration in the docs [here](https://github.com/vercel/styled-jsx#rendering-in-tests)
```
{
  "presets": ["next/babel"],
  "env": {
    "production": {
      "plugins": ["styled-jsx/babel"]
    },
    "development": {
      "plugins": ["styled-jsx/babel"]
    },
    "test": {
      "plugins": ["styled-jsx/babel-test"]
    }
  }
}
```
**And** add a styled jsx to the index file. 
```
<style jsx>{`
    main {
        background-color: red;
    }
`}
</style>
```
**Then** run tests via `npm run test`
**Actual**: My snaphots gets a jsx-123 ❌ id
**Expected**: My snapshots shouldn't have any ids given I'm running in a test environnement [based on this doc](https://github.com/vercel/styled-jsx#rendering-in-tests)  ✅ 

[That commit](https://github.com/vercel/next.js/pull/7747) should have fixed that issue, maybe there was regression
@timneutkens Maybe you could point me in the right direction  - I might be using the babel config wrong. 

* OS: Mac 10.14.9
* Browser: Node v.13.14.1
* styled-jsx (version): 3.3.0
* Next: 9.9.4

Tried reverting styled-jsx until version as far as 2.2.7  and this still fails on Next 9.9.4 version

**Comment by giuseppeg** [comment]
Hi @etiennejcharles Next's preset includes styled-jsx so in order to configure it you need to pass options to it as described here https://nextjs.org/docs/advanced-features/customizing-babel-config

Specifically the option for disabling the babel plugin is `"babel-test": true`.

Finally make sure that `process.env.NODE_ENV` is set to `test`.

hope this helps

**Comment by etiennejcharles** [comment]
I took me some time to get it, but I think what you meant is this: 

```
{
  "presets": ["next/babel"],
  "env": {
    "test": {
      "presets": [
        [
          "next/babel",
          {
            "styled-jsx": {
              "babel-test": true
            }
          }
        ]
      ]
    }
  }
}
```

**Comment by ivan-kleshnin** [comment]
@etiennejcharles thanks for the snippet. How did you fix the inevitable consequent error:

```
  styled-jsx/css: if you are getting this error it means that your `css` tagged template literals were not transpiled.

    > 29 | let styles = css`  
         |                  ^
      30 |   .icon {
      31 |     align-items: center;
      32 |     display: inline-flex;
```

**Comment by Hyokune** [comment]
> I took me some time to get it, but I think what you meant is this:
> 
> ```
> {
>   "presets": ["next/babel"],
>   "env": {
>     "test": {
>       "presets": [
>         [
>           "next/babel",
>           {
>             "styled-jsx": {
>               "babel-test": true
>             }
>           }
>         ]
>       ]
>     }
>   }
> }
> ```
> 
> Is there a way to simplify that ? 😆
> Il probably provide a PR -
> I've been debugging the nextjs/preset file by console logging it (didn't have a better idea to debug this. )
> 
> If that's the way, then Il probably submit a PR in the docs

I've added this to my `.babelrc` file and also set `NODE_ENV=test` before running the test command, but I still seem to getting the error `Warning: Received `true` for a non-boolean attribute `jsx`.

Is there anything else I've missed for this to work?

**Comment by etiennejcharles** [comment]
A bit aggressive ->
![image](https://user-images.githubusercontent.com/2872476/110844556-8b9d6800-8277-11eb-86e4-e8b5bf3c43b4.png)

But this is what I do in my `jest.config.js` file
To force my tests to run in the test environnement
