### ISSUE TITLE
What is the difference of :global and <style jsx global> ? And why do we have both?

### ISSUE THREAD

**Issue by JoseFMP** [vercel/styled-jsx#655]

**Comment by lachlanjc** [comment]
They're both useful in different contexts!

`:global` is handy when you want to reference children or parents in the same selector as a scoped style, e.g. `:global(header) h1` will style only the current component's h1 while in any type of `header` element.

The `global` prop is easier when you have several entirely-global styles to apply, such as for `html` & `body`.

**Comment by huozhi** [comment]
@lachlanjc Thanks for the explanation!
