### ISSUE TITLE
Store styled-jsx inside of a variable

### ISSUE THREAD

**Issue by IcyFoxe** [vercel/styled-jsx#659]
## Feature request

Would it possible to store styled-jsx contents inside of a variable, for sepparation of concerns?

This is what I tried:

```
<style jsx>{myStyle}</style>
```

```
let myStyle = `
  p {
    color: blue;
  }
`
```

However this doesn't seem to work.

Anyone knows, whether it's possible to sepparate styled-jsx from the rest of the code?

**Comment by Divlo** [comment]
@IcyFoxe It is explained in the README.md file : https://github.com/vercel/styled-jsx#external-css-and-styles-outside-of-the-component.

**Comment by eliasturbay** [comment]
Hi @Divlo, I was wondering if there's a way to do something like that but with content that is fetched thru an API.
So the `myStyle` variable is actually fetched and then I need to apply those styles to my component. I've been reading the docs but I can't figure that out yet :( 
I will highly appreciate any help on that matter, thx!

**Comment by IcyFoxe** [comment]
Now that I got back into it, and tested it out, it certainly works Divlo.
I can store my component CSS in sepparate files, which helps a lot with readability.

Thanks for pointing it out.
