### ISSUE TITLE
support styled-jsx for tsloader/typesrcipt apps

### ISSUE THREAD

**Issue by laurencefass** [vercel/styled-jsx#661]
👋 friend. Welcome to styled-jsx and thanks for contributing!

---

#### Do you want to request a *feature* or report a *bug*?
feature

#### What is the current behavior?
I can find any documentation for integrating styled-jsx into a typescript app loaded with tsloader. tsloader says it plays nicely with babel but the simple inclusion of a plugin doesn't work in my case.

```
     "plugins": [
       // additional plugins
       "styled-jsx/babel"
     ]

```
#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

n/a

#### What is the expected behavior?
easily integrate styled-jsx into projects using tsloader

#### Environment (include versions)

* OS: Linux
* Browser: any
* styled-jsx (version): latest

#### Did this work in previous versions?
im sure there is a valid configuration but i cant see it.

**Comment by giuseppeg** [comment]
@laurencefass  ts-loader is a webpack loader right? If so I think it uses tsc (the TypeScript compiler).. anyway have you checked this https://www.npmjs.com/package/ts-loader#babel ?

**Comment by hrasoa** [comment]
I just run into the same issue, here's a repo to reproduce: https://github.com/hrasoa/styled-ts.
When commenting the ```ts-loader```, it works fine.

**Comment by huozhi** [comment]
Hi @hrasoa , the order of ts-loader and babel-loader should be swapped to let webpack apply babel transform first. And you need to let babel be able to parse ts syntax as well so that ts-loader could consume the valid transformed code.

I created a [patch commit](https://github.com/beeebox/styled-ts/commit/338dee16fd5808546700aeca1c8a533eb91031d9) here to make it work.

**Comment by hrasoa** [comment]
Thanks @huozhi I got it, it works. One last question, why should we have to add ```declare module 'styled-jsx/style'``` as ```styled-jsx``` has already his own type definitions ?

**Comment by huozhi** [comment]
Oh yeah there's a way to avoid doing this. Keep the origin order of loaders, but let tsc preserve the jsx syntax for babel.
I filed a PR to your reproduction [here](https://github.com/hrasoa/styled-ts/pull/1) with all detailed changes.

**Comment by hrasoa** [comment]
Ok I saw it, but shouldn't we use ```"jsx": "react-jsx"``` for ```react > 17``` ?

**Comment by huozhi** [comment]
The idea is to let ts-loader parse the jsx with typings without transform. and then babel could apply styled-jsx transforms onto the raw jsx. So that babel do the most of the work. I found this on ts-loader's readme, where they use the similar approach for transpiling vue
