### ISSUE TITLE
VSCode Toggle Line Comment always mark styled-jsx code using jsx comment style

### ISSUE THREAD

**Issue by stomvi** [vercel/styled-jsx#663]
#### Do you want to request a *feature* or report a *bug*?
Feature

#### What is the current behavior?
VSCode `Toggle Line Comment` always mark styled-jsx code using jsx comment style `{/* */}`. I guess VSCode just add/remove comment based on the file type and the code block which the line is located. So maybe there is a missing Babel config which should indicate the styled-jsx block. I'm using Babel Javascript extension [michaelgmcd/vscode-language-babel](https://github.com/michaelgmcd/vscode-language-babel) as my javascript syntax tool.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. Just `Toggle Line Comment` in one of the styled-jsx block

```css
.header {
  font-size: 1.75rem;
  {/* font-weight: 100; */}
}
```

#### What is the expected behavior?
styled-jsx block should use `/**/` as comment style.

#### Environment (include versions)

* OS: Mac OS
* styled-jsx (version): version that comes with `next 9.5.2`
* michaelgmcd/vscode-language-babel: v0.0.29
* iFwu/vscode-styled-jsx: v2.0.0

**Comment by giuseppeg** [comment]
@stomvi hi unfortunately this isn't something we can control. Styles are written in JavaScript strings and that's probably why VSCode turns them into expressions (it doesn't know that the content is CSS). You may want to open an issue on VSCode and ask if it is possible to fix that.
