### ISSUE TITLE
The styled-jsx does not render the style when the Browser has js disabled (Rollup and styled-jsx)

### ISSUE THREAD

**Issue by dionatanaraujo** [vercel/styled-jsx#666]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?

I'm working on a blog project and one of the requirements is that the blog works even if the browser has javascript disabled. When using the project "https://github.com/dionatanaraujo/rollup-styled-jsx" a fork of "https://github.com/Tomekmularczyk/rollup-styled-jsx", we noticed that when disabling the browser javascript the components are not carrying styling.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

How simulate the error:

1. Enter in the root project and run npm install and then npm run build:prod
2. Enter in the demo project cd demo and run npm install and then npm run dev
3. Access the browser http://localhost:3000, go to settings and disable javascript.
4. Note that the styles will not be loaded.

Please, is there something wrong or missing in this configuration so that the styles work correctly when javascript is disabled?

Component library with js enabled (work's fine):
<img width="260" alt="Screen Shot 2020-09-07 at 3 21 33 PM" src="https://user-images.githubusercontent.com/8082750/92411417-2d53c900-f11e-11ea-9755-e1cacbed91b0.png">

Component library with js disabled (styles don't work):
<img width="497" alt="Screen Shot 2020-09-07 at 3 22 17 PM" src="https://user-images.githubusercontent.com/8082750/92411483-6c821a00-f11e-11ea-83fc-6792803f0b3b.png">

The project that is in / demo and was built using Next.js to work with SSR. Please, if anyone can help with that it would be very rewarding.

#### What is the expected behavior?
Styles should working when browser has javascript disabled

#### Environment (include versions)

* OS: MacOS 10.15 Catalina
* Browser: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
* styled-jsx (version): 3.3.0

**Comment by huozhi** [comment]
It requires server side to collect all the styles and flush to client when you need to render styles without javascript. Next.js does the work so you can do it within Next.js. By default styled-jsx will still inject styles in client rendering if there's no styles extraction for style registry.

Please checkout https://github.com/vercel/styled-jsx#server-side-rendering
