### ISSUE TITLE
How can I hide class names from showing in the DOM?

### ISSUE THREAD

**Issue by mattjis** [vercel/styled-jsx#667]
I'm building a widget that needs to look the same no matter where it has been embedded.

At the moment the elements have class names such as: `jsx-2190104459 button`. The `button` part of the class is the one causing issues, as the user's site occasionally has their own `.button ` or whatever class for something unrelated and the rules are clashing.

Can it be hidden? I like using generic words internally.

**Edit:** I just realised the `jsx-2190104459` is not for each element, but the whole scope. So just hiding the class will not work.
Is there any solution, besides creating complex internal class names?

**Comment by davoodfox** [comment]
same issue
