### ISSUE TITLE
Unable to import module correctly and build with Rollup

### ISSUE THREAD

**Issue by RobinCodeX** [vercel/styled-jsx#669]
Codesandbox: https://codesandbox.io/s/musing-meninsky-bx1kl?file=/package.json:1591-1596
[public/dist/Demo.js#L2763](https://github.com/RobinCodeX/rollup-react-project-example/blob/b5d9ac1c3f0c4fa009fe0fe4236a7f76cf937c31/public/dist/Demo.js#L2763) Here should be `var style$1 = style.default;`
[public/dist/Demo.js#L28982](https://github.com/RobinCodeX/rollup-react-project-example/blob/b5d9ac1c3f0c4fa009fe0fe4236a7f76cf937c31/public/dist/Demo.js#L28982)

Does this mean that styled-jsx is not compatible with Rollup or my configuration is incorrect?

#### Environment (include versions)

* OS: Windows 10
* Browser: Microsoft Edge 85
* styled-jsx (version): 3.3.0

**Comment by danchitnis** [comment]
Any update on this? The problem gets fixed when manually overwriting this line from `var style$1 = style` to `var style$1 = style.default`
