### ISSUE TITLE
Question: Can we use rupture/nib with Styled JSX + Stylus?

### ISSUE THREAD

**Issue by mavichow** [vercel/styled-jsx#686]
#### What is the current behavior?
[Styled JSX Stylus](https://www.npmjs.com/package/styled-jsx-plugin-stylus) is not compiling "[rupture](https://jescalan.github.io/rupture/)" +tablet() +to-width(768px) functions.

#### Step to reproduce

1. npx create-next-app
2. cd my-app
3. npm install --save styled-jsx
4. npm install --save-dev stylus styled-jsx-plugin-stylus rupture nib
5. touch .babelrc
6. Below is both my **/.babelrc** and **/pages/index.js** code

```
//.babelrc
{
    "presets": [
        [
            "next/babel",
            {
                "styled-jsx": {
                    "plugins": [
                        ["styled-jsx-plugin-stylus",{
                            "stylusOptions" : {
                                use : ["nib","rupture"]
                            }
                        }]
                    ]
                }
            }
        ]
    ]
}

//pages/index.js
export default function Home() {
  return (
    <div>
      <style jsx>{`
        h1
          background blue
          color white
          +tablet()
            background red
     `}</style>
      <main>
        <h1>Hello</h1>
      </main>
    </div>
  )
}
```

_I've also try Stylus Options method on [styled-jsx-plugin-stylus](https://www.npmjs.com/package/styled-jsx-plugin-stylus#stylus-options) but encounter syntax error while adding/configuring my stylus options on .babelrc file_

#### What is the expected behavior?
After running `npm run dev` Html background will change from blue to red in Tablet viewport.

#### Environment (include versions)

* OS: MacOS v11.0.1
* Browser: Google Chrome v86.0.4240.198
* styled-jsx (version): ^3.3.2
* styled-jsx-plugin-stylus: 0.0.4
* next:  10.0.3

**Comment by giuseppeg** [comment]
Hey there thanks for taking the time to write a comprehensive issue description!! 

I am not very familiar with both stylus and repture/nib. You might want to ask the author of styled-jsx-plugin-stylus https://github.com/omardelarosa/styled-jsx-plugin-stylus - I'll close this issue as supporting stylus is out of the scope of this project.
