### ISSUE TITLE
Should filter out undefined and null

### ISSUE THREAD

**Issue by J-env** [vercel/styled-jsx#687]
![image](https://user-images.githubusercontent.com/25259920/101870723-2923c580-3bbd-11eb-9ebc-a556218fc40e.png)

Should filter out undefined and null class names.

I think you can add the attribute dynamic. Then only filter the content of these style components.

---

**Comment by giuseppeg** [comment]
Hi there thanks for bringing this up. It might be easier if you define sensible defaults for the props so that they are never undefined/null or perhaps toggle a class name if those are falsy and should not apply.
