### ISSUE TITLE
import _JSXStyle2 from "styled-jsx/style"; when my components's props use destructuring

### ISSUE THREAD

**Issue by SweetSweetME** [vercel/styled-jsx#696]
👋 friend. Welcome to styled-jsx and thanks for contributing!

⚠️ IMPORTANT ⚠️

If you need help or have a question about styled-jsx please ask it on Spectrum https://spectrum.chat/styled-jsx or join our Slack community at https://zeit.chat and ask it in the `#next` channel.

Before you open a new issue please take a look at our [**Frequent Asked Questions**](https://github.com/zeit/styled-jsx#faq) and [**open issues**](https://github.com/zeit/styled-jsx/issues).

Remember, often time asking in chat or looking at the FAQ/issues can be *faster than waiting for us to reply to a new issue**.

If you are here to report a bug or request a feature please remove this introductory section and fill out the information below!

---

#### What is the current behavior?

when i use destructuring in component, i will got an error about _JSXStyle because of `import _JSXStyle2 from "styled-jsx/style";` not `import _JSXStyle from "styled-jsx/style";`

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. webpack 4.32.2
2. @babel/core 7.4.5

#### What is the expected behavior?
normal working
#### Environment (include versions)

* OS: 
* Browser:
* styled-jsx (version): 3.4.0 and 3.4.1；both happen

**Comment by jaydenseric** [comment]
Can't reproduce:

https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAbzkwgjgF8Gc98AjFKM88kgAe1eABMkmFAFcANlmkA7DMAiK4AMSYAKAJR1ycOERjSo67YaNwAPGOAA3AHxXrtgM4wAnrKRwAVu5CTrQABq5ucPYOBpGRaBCy0ABcxkhiFHFGLBFGoSw2APSePkgubkXR5XC6FCwUQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=true&targets=&version=7.12.12&externalPlugins=babel-plugin-styled-jsx-repl%400.1.0

<img width="943" alt="Screen Shot 2021-01-26 at 11 43 27 pm" src="https://user-images.githubusercontent.com/1754873/105846473-583cac00-6030-11eb-8372-fc678abb7849.png">

Please provide a minimum reproduction in the Babel REPL.

**Comment by SweetSweetME** [comment]
please:https://github.com/SweetSweetME/styled-jsx-test

**Comment by unix** [comment]
I also have this issue with the latest version, when I use version `styled-jsx@3.3.0`, everything works fine.
