### ISSUE TITLE
Bad TypeScript types

### ISSUE THREAD

**Issue by travigd** [vercel/styled-jsx#698]
#### Do you want to request a *feature* or report a *bug*?

Bug/issue.

#### What is the current behavior?

The current types list typings in package.json which claim that `styled-jsx` exports `css`... which isn't true. You actually need to import `styled-jsx/css`.

This also requires there to be a root level `css.d.ts` file (at the same level as `css.js` in the root of the package, not inside `typings/`).

#### Environment (include versions)

* styled-jsx (version): 3.4.2

**Comment by Divlo** [comment]
Maybe it was my bad : https://github.com/vercel/styled-jsx/pull/692
Could you open a PR to fix the types ? Thanks! :smile: 
@travigd
