### ISSUE TITLE
type error `Property 'resolve' does not exist on type 'typeof import("node_modules/styled-jsx/css")`

### ISSUE THREAD

**Issue by rudyal** [vercel/styled-jsx#701]
#### Do you want to request a *feature* or report a *bug*?
bug
#### What is the current behavior?
type error for css.d.ts
`Property 'resolve' does not exist on type 'typeof import("node_modules/styled-jsx/css")'.`
#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. import and use css.resolve in tsx file `import css from 'styled-jsx/css';`
2. compile types `tsc`

#### What is the expected behavior?
No type errors

#### Environment (include versions)
* OS: macOS catalina
* Browser: chrome 88
* styled-jsx (version): 3.4.4

#### Did this work in previous versions?
yes 3.4.2

**Comment by valse** [comment]
I don't know if it's a breaking change but with a single named import it works again:

`import { css } from "styled-jsx/css"`

**Comment by AleksandrHovhannisyan** [comment]
Out of curiosity: Why did a patch-level upgrade cause things to break? I can't see why the default export would've become a named one, but it did in 3.4.4.

**Comment by scalarerp** [comment]
Same error with  create-react-app, 
error with:  import { css } from "styled-jsx/css" or import  css  from "styled-jsx/css"

**Comment by amccloud** [comment]
Can confirm this now works for 3.4.4 in dev and build:

```js
import { css } from "styled-jsx/css"
```

While the old import only works in dev for me:

```js
import css from "styled-jsx/css"
```

```
Type error: Property 'resolve' does not exist on type 'typeof import("/app/node_modules/styled-jsx/css")'.
```

**Comment by huozhi** [comment]
It's already fixed in new versions of styled-jsx
