### ISSUE TITLE
Get `css_1.css is not a function` error when use external styles

### ISSUE THREAD

**Issue by PhanDungTri** [vercel/styled-jsx#706]
#### Do you want to request a *feature* or report a *bug*?
Bug
#### What is the current behavior?
When I use an external style, the browser throws the error telling that the `css` is not a function

![Screenshot from 2021-02-28 22-06-54](https://user-images.githubusercontent.com/26342804/109442044-a1d24980-7a69-11eb-9067-9b124711237f.png)

This doesn't happen when I write style inside component. Here is the [sandbox](https://codesandbox.io/s/exciting-sun-hxb2i).

#### Environment

* OS: Manjaro Linux Nibia 20.2.1
* Browser: Chromium Version 88.0.4324.182 (Official Build) Arch Linux (64-bit)
* `styled-jsx` 3.4.4
* `parcel-bundler` 1.6.1

**Comment by huozhi** [comment]
`css` is default exports, you should use

```diff
- import { css } from 'styled-jsx/css'
+ import css from 'styled-jsx/css'
```

https://codesandbox.io/s/great-hoover-zsd0j-zsd0j?file=/src/index.js
