### ISSUE TITLE
Plugin processing not applied to dynamic styles

### ISSUE THREAD

**Issue by madeleineostoja** [vercel/styled-jsx#712]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
Styles used dynamically do not get passed to styled-jsx plugins (eg: postcss)

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. Add styled-jsx plugin (eg: postcss)
2. Use dynamic styles that would require that plugin to be valid
3. Observe the invalid/unprocessed styles output

Eg: assume you have some kind of nesting support added by postcss (like `postcss-preset-env`), this fails and outputs the nesting straight to the browser

```jsx
const condition = true;

<style jsx>{`
 .foo {
   color: pink;
   ${condition && `& > .bar { color: blue; }`}
 }
`}</style>
```

#### What is the expected behavior?

Dynamic styles should be processed with plugins

#### Environment (include versions)

* OS: macOS
* Browser: Chrome
* styled-jsx (version): NextJS 10

#### Did this work in previous versions?

Not to my knowledge

**Comment by hpachy** [comment]
same problem...

**Comment by giuseppeg** [comment]
Hi there! Since styled-jsx compiles styles at build time, it cannot preprocess dynamic styles, this is a limitation that is mentioned in the docs

> Plugins won't transform expressions (eg. dynamic styles).

more here https://github.com/vercel/styled-jsx#css-preprocessing-via-plugins

**Comment by hpachy** [comment]
Just to be sure to understand, I'm ok with the fact which is the style is create at the compilation time and that's it, so the following code is not working great no problem :

```js
  return (
    <div className={`wrapper-split ${styles.wrapperSplit}`}>
      {memoSplitScreen}
      <style global jsx>{`
        ${style} .wrapper-split {
          overflow: hidden;
        }
      `}</style>
    </div>
  );
```

but why this following code work ?

```js
  return (
    <div className={`wrapper-split ${styles.wrapperSplit}`}>
      {style && (
        <style jsx global>
          {`
            .wrapper-split div.split-img #${data.title} img {
              ${style}
            }
          `}
        </style>
      )}
    </div>
  );
```

I mean the only different between is :

-In the first code style equal to something like 'div[class^="toto"] .titi {background: red}' ❌ not working

-In the second code style equal to something like 'background : red' + a dynamically definition of id in the styled-jsx tag ✅ workgin

**Comment by giuseppeg** [comment]
```jsx
{style && (
        <style jsx global>
```

Conditional styles like this are not allowed and you should get an error.

```js
.wrapper-split div.split-img #${data.title} img {
  ${style}
}
```

Here the declarations (`style`) are not static and are not compiled by styled-jsx.

If you need conditional styles, maybe you can check out this feature https://github.com/vercel/styled-jsx#external-css-and-styles-outside-of-the-component and define them outside the component explicitly.

If you need further help, please create a small test case on CodeSandbox using the Next.js template. It will be easier for me to understand your actual use case.

**Comment by hpachy** [comment]
I tried an other solution with the following code on the documentation you gave me. following code : 

```js
import React from "react";
import css from "styled-jsx/css";

function getLinkStyles(color: string) {
  return css.resolve`
    div > h1 {
      color: ${color};
    }
  `;
}

export default () => {
  const { className, styles } = getLinkStyles("red");

  return (
    <div>
      <div className={className}>
        <h1>tot</h1>
      </div>
      {styles}
    </div>
  );
};

```

But I got something annoying when I tried to add selector directly after each I got >jsx-1807396575 
in my case so I got wrong selector and no style on my elements...

![Uploading Capture d’écran, le 2021-03-31 à 16.20.53.png…]()
