### ISSUE TITLE
Create React App 

### ISSUE THREAD

**Issue by cubecleveland** [vercel/styled-jsx#745]
Hello, this is probably not an issue and aplologize for posting it here but right out of the box im using the library with craete-react-app.

Everything works great but all the styles are being applied globally and are not scoped to the compoeennt.

this code:
```jsx
 <button
      disabled={props.disabled || props.isLoading}
      type="button"
      className="secondary-button"
      {...props}
    >
      {props.disabled && <ButtonLoader />}
      {props.children}
      <style jsx>{`
        button {
          display: flex;
          flex-direction: row;
          align-items: center;
          padding: 8px 16px;
          height: 40px;
          background: #eefff9;
          border-radius: 5px;
          font-style: normal;
          font-weight: 500;
          font-size: 14px;
          color: #00a96c;
        }
        button:hover {
          background: #d8fff1;
          color: #008e5b;
          transform: all ease 2s;
        }
      `}</style>
    </button>
```
styles all the butttons in the document.

Anything we are doing wring?

**Comment by huozhi** [comment]
Hi, do you have a full reproduction for this that can help us investigate?

**Comment by huozhi** [comment]
Close as no interaction for a long time. feel free to open a new one if you still have issue with it
