### ISSUE TITLE
Different versions of styled-jsx lead to FOUC

### ISSUE THREAD

**Issue by Regaddi** [vercel/styled-jsx#751]
#### Do you want to request a *feature* or report a *bug*?

It's not necessarily a bug, nor a feature request. Probably something in between.

#### What is the current behavior?

Given a monorepository with 2 packages:

- A package `example` running a Next.js project (e.g. `next@11.1.2`), where `styled-jsx@4.0.1` is a direct dependency
- A package `shared` with shared React components, using `styled-jsx@3.3.2`

When the `example` project includes components from `shared` and the app is run in `production` mode, the whole page has a FOUC on every page load.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. Clone https://github.com/Regaddi/yarn-next-styled-jsx-fouc
2. Follow reproduction steps as described in readme

#### What is the expected behavior?

No FOUC.

#### Environment (include versions)

* OS: macOS 11.6
* Browser: Chrome 94
* styled-jsx (version): 3.3.2 / 4.0.1

#### Did this work in previous versions?

No, IIRC this did not work before.

**Comment by huozhi** [comment]
@Regaddi Why you'd want to stick styled-jsx into `3.x` version in the `shared` components? Could you try to make `styled-jsx` as peer dependency in your shared libs then when it's been adopted to a next.js app or other app with styled-jsx installed, they can share the styled-jsx as common.

**Comment by scottccoates** [comment]
@Regaddi Thank you for making a such a detailed reproduction. After upgrading to next 12, I am running into the same issue. 

My web app is at Next 12 and therefore Styled-Jsx v5, but my shared components depend on Styled-Jsx v3. 

As I'm new to monorepos, why isn't the default for yarn to effectively "hoist" Styled-Jsx v5 into my web app (next 12)'s own `node_modules` folder? And a follow up to that, is there anyway I can achieve this with my `package.json` file in the root of my monorepo? The `resolutions` key isn't working for me…

**Comment by scottccoates** [comment]
**A good way to test this is to disable javascript altogether and reload the page. You will see no styling at all.** Is it possible that webpack is somehow picking up the wrong version of `styled-jsx` at compile time?

**Comment by huozhi** [comment]
Sorry for the late response, but I think it's like React when you're building React libraries, mark it as peer dependency. Then when it's integrated into the app where it has styled-jsx or a next.js app where styled-jsx is supported out of box, they share the same styled-jsx.

For library development, you can keep it as a `devDependency` and add to `peerDependencies` at the same time
