### ISSUE TITLE
bug: change `<style jsx global>` to `<style jsx>` (or vice versa) and hot reload doesn't notice

### ISSUE THREAD

**Issue by CarltonHenderson** [vercel/styled-jsx#757]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What is the current behavior?

```
export default function IndexPage() {
  return (
    <div>
      <SubComponent />
      <style jsx global>{`
        span {
          color: green;
        }
      `}</style>
    </div>
  );
}

function SubComponent() {
  return <span>should change from green to black</span>;
}
```

1. start with the code above
2. remove `global` from `<style jsx global>`
3. save the file
4. see hot reload take place
5. **expect** to see the text in the span change from green to black but **actually** it stays green
6. refresh the page
7. see the text finally change to black as expected
6. add `global` back to `<style jsx global>`
7. save the file
8. see hot reload take place
9. **expect** to see the text in the span change from black to  green but **actually** it stays black
6. refresh the page
7. see the text finally change to black as expected

https://codesandbox.io/s/clever-hermann-nzfme?file=/pages/index.js:235-268

#### Environment (include versions)

* OS: codesandbox or linux
* Browser: chrome
* styled-jsx (version): 5.0.0-beta.3

#### Did this work in previous versions?

It is also buggy in Next 11.1:
https://codesandbox.io/s/objective-firefly-85jm7?file=/pages/index.js

**Comment by huozhi** [comment]
Can you upgrade to next 12.0.2-canary.9 it solved the issue for me.
