### ISSUE TITLE
Bug: After update to 5.0.0-beta.3, storybook stopped embedding CSS

### ISSUE THREAD

**Issue by igorshmukler** [vercel/styled-jsx#761]
#### Do you want to request a *feature* or report a *bug*?

I believe that there might be a bug in the `5.0.0-beta.3` release.

#### What is the current behavior?

Currently, when CSS is created as:
```
import css from 'styled-jsx/css';
import { colors, screen } from 'components/styles/variables';
const styles = css`
  .search-result {
  ...
  }
`;
export default styles;
```
Embedding the above `CSS` as:

```
  return (
    <div className="search-result" data-testid="search-result" onClick={onClick}>
      <style jsx>{styles}</style>
      ...
    </div>
  );
```
Results in the correctly generated class names, and NO styles. The `<style>...</style>` is just not there.

####

Make a component using `styled-jsx/css` and embed the resulting `CSS` with `<style jsx>{styles}</style>`.

#### What is the expected behavior?

Styles should be embedded into the elements.

#### Environment (include versions)

* OS: MacOS
* Browser: Chrome, Safari, Firefox
* styled-jsx (version): 5.0.0-beta.3

#### Did this work in previous versions?

Yes, this worked fine in 3.3.1 and 3.3.2

Downgrading returning the lost functionality.

**Comment by huozhi** [comment]
Are you directly using styled-jsx with babel or you're using it along with next.js? And additional information can be provided?

**Comment by bspksal** [comment]
I am also having this problem

**Comment by igorshmukler** [comment]
> Are you directly using styled-jsx with babel or you're using it along with next.js? And additional information can be provided?

I am running NextJS 12.0.3.

My storybook webpack config is below:

```
const webpack = require('webpack');

module.exports = ({ config }) => {
  // Fill in process.env on the client
  config.plugins.push(
    new webpack.DefinePlugin({
      'process.serializedEnv': {},
    })
  );

  // Sentry requires different packages for front and back end,
  // but in storybook we know it's always client side
  config.resolve.alias = {
    'sentry-alias': '@sentry/browser',
    '@/remoteConfig': './standardRemoteConfig',
  };

  config.module.rules.push({
    test: /\.md$/,
    loader: "raw-loader",
  }),

  config.externals = [...(config.externals || []), 'fs', 'net'];

  config.resolve.extensions.push('.md');

  config.resolve.fallback = {
    "https": false,
    "stream": false,
  };

  return config;
};
```
and my main.js
```
module.exports = {
  core: {
    builder: 'webpack5',
  },
  stories: ['../stories/**/*.stories.tsx'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-backgrounds',
    '@storybook/addon-knobs',
    '@storybook/addon-viewport',
    '@storybook/addon-a11y',
    'storybook-addon-paddings',
  ],
};
```
All standard stuff. This worked fine before the upgrade to 5.0.0.

**Comment by ngtongsheng** [comment]
I am running the same issue with NextJS 12.0.3.

**Comment by huozhi** [comment]
Can you try to add the below code snippet into your preview.js config?

```js
// .storybook/preview.js
import { StyleRegistry } from 'styled-jsx'

export const decorators = [
  (Story) => (
    <StyleRegistry>
      <Story />
    </StyleRegistry>
  ),
]
```

According to the [v5 doc](https://github.com/vercel/styled-jsx/tree/beta#server-side-rendering) we introduce a new registry here to make it styled-jsx work better with react 18 concurrent rendering. Will make the document ready at default branch asap.

Close this issue as the above solution works on my side with next.js `with-storybook` exmaple. Le me know if it solves your problem

**Comment by huozhi** [comment]
Hi y'all if you're upgrading next.js to v12.0.8-canary.13 you don't need the change mentioned above. It will work as before
