### ISSUE TITLE
ReferenceError: _JSXStyle2 is not defined

### ISSUE THREAD

**Issue by epomatti** [vercel/styled-jsx#762]
#### Do you want to request a _feature_ or report a _bug_?
Looks like a bug but might be misconfiguration on my part.

#### What is the current behavior?
I have these styles:

```js
function myMehod() {
  const height = randomHeight();
  return (<div>
    <style jsx>{`
  .myStyle {
    position: fixed;
    animation: ${keyf} 2s linear;
    animation-timing-function: ease-in ;
    left: -120px;
    top: ${height}%;
    transform: rotate(45deg);
  }

  @keyframes look {
    0% {
        left: -120px;
    }
    5% {
        left: -45px;                
    }
    95% {
        left: -45px;                
    } 
    100% {
        left: -120px;
    }
  } 
  `}</style>
  </div>)
}
```
And getting this error:

![image](https://user-images.githubusercontent.com/6530769/143479154-a418b8cc-37ef-4a9e-8e62-65ba45593a10.png)

If I import `_JSXStyle2` it keeps incrementing:

![image](https://user-images.githubusercontent.com/6530769/143479567-c13a43ac-95bd-486e-9adc-6e93f8cd4289.png)

**.babelrc**

```json
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "styled-jsx/babel"
    ]
  ]
}
```

#### Environment (include versions)

- OS: Linux WSL2
- Browser: Chrome Version 96.0.4664.45 (Official Build) (64-bit)
- styled-jsx (version): ^4.0.1

#### Did this work in previous versions?
This is the first version I'm using.

**Comment by huozhi** [comment]
Are you using next.js? If so can you try to remove the `"plugins"` section in your babel config to see if it works?

**Comment by huozhi** [comment]
If you still have this issue, feel free to post updates and we can reopen it. 🙏
