### ISSUE TITLE
Confusing section on SSR in readme

### ISSUE THREAD

**Issue by miachenmtl** [vercel/styled-jsx#763]
#### Do you want to request a _feature_ or report a _bug_?

_Feature_: Please clarify documentation for SSR in v3

#### What is the current behavior?

I am migrating a codebase from Next 10 to 12, and got an error saying webpack cannot resolve module `styled-jsx/server`.  Eventually I figured that that module was from the [v2 readme](https://github.com/vercel/styled-jsx/tree/v2#server-side-rendering), but I was confused because I couldn't find anything describing the API change. The sentence 'It's _paramount_ that you use one of these two functions...' is particularly confusing in the v3 readme, because looking at the v2 docs, it's clear it's in reference to `flush` vs `flushToHTML`, but that distinction seems not to be there in v3?

A brief explanation of how to migrate an API using `styled-jsx/server` to use `StyleRegistry` would be much appreciated. Thank you!

**Comment by huozhi** [comment]
Hi @miachenmtl, thanks for reaching out I'm working on the doc upgration now. Could you provide the case that how you integrate `styled-jsx` with nextjs? Did you do any customzation on document page? like manually flush styles stuff?

**Comment by huozhi** [comment]
I submitted a [PR](https://github.com/vercel/next.js/pull/32594) here to update the custom styled-jsx in document page, hope this could help a little before the doc is ready

**Comment by miachenmtl** [comment]
> I submitted a [PR](https://github.com/vercel/next.js/pull/32594) here to update the custom styled-jsx in document page, hope this could help a little before the doc is ready

Thanks for the quick response! Yes, I was flushing styles on the _document page. I noticed in the PR that there's no flush in the updated example--is flushing done automatically? I was just following the example from the styled-jsx readme which does have `registry.flush`in it.

**Comment by huozhi** [comment]
With using styled-jsx inside next.js: If you don't need to apply `nonce` to your style tags for CSP purpose, you can just use following code to access styles in _document page

```js
static async getInitialProps(ctx) {
  return await ctx.defaultGetInitialProps(ctx)
}
```

Or use next.js above `v12.0.8-canary.10` with following code to apply it
```diff
static async getInitialProps(ctx) {
-  return await ctx.defaultGetInitialProps(ctx)
+  return await ctx.defaultGetInitialProps(ctx, { nonce })
}
```

Then next.js will consume those styles (array) and map them into react nodes under head element. So you don't need to have other extra customization.
