### ISSUE TITLE
styled-jsx overwrites className set by functions

### ISSUE THREAD

**Issue by denkristoffer** [vercel/styled-jsx#764]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What is the current behavior?

When you spread an object returned by a function, the prop className is overwritten completely by styled-jsx.

I've run into this issue when using styled-jsx with react-table, which has a convention of spreading the return values of prop getters on table elements. This behaviour is also mentioned in https://github.com/vercel/styled-jsx/issues/539#issuecomment-689622415 which includes the following example.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

https://codesandbox.io/s/nifty-jennings-dl164?file=/pages/index.js

#### What is the expected behavior?

`class` should both the generated class and `my-class`

**Comment by huozhi** [comment]
You can define it as a veriable first then spread the result to the jsx component, babel or swc plugin will read it and merge the `className` from it.

```jsx
export default function IndexPage() {
  const computeProps = () => ({ className: "my-class" });

  const rest = computeProps();
  return (
    <>
      <div {...rest}>Hello World</div>
      <style jsx>{`
        div { color: blue; }
      `}</style>
    </>
  );
}
```
