### ISSUE TITLE
styled-jsx, used in the thin wrapper solid-styled-jsx, seems to get `class=` props wrong.

### ISSUE THREAD

**Issue by trusktr** [vercel/styled-jsx#772]
Hello! Nice work. This offers similar to `<style scoped>` in Vue, making it easy to port from Vue.

#### Do you want to request a _feature_ or report a _bug_?

I'm not sure. 

#### What is the current behavior?

`class=` is not a React thing, but it is in Solid.js. Solid made a very small wrapper around styled-jsx to bring it to Solid's JSX (https://github.com/solidjs/solid-styled-jsx).

When writing some JSX like `<div class="foo">` this causes the output to have something like `<div class="undefinedjsx-3266584492undefined">`. Described here: https://github.com/solidjs/solid-styled-jsx/issues/1

Luckily Solid.js also supports `className=` and using that works fine, so changing the above to `<div className="foo">` works.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

TODO: make repro

#### What is the expected behavior?

It _seems_ to me (but I'm not 100% sure, but based on how small Solid's wrapper is) that styled-jsx's Babel transform is _trying_ to do something with `class=` props but not getting it quite right compared to with `className=`.

Is my hunch correct?

#### Environment (include versions)

- Version of styled-jsx (or next.js if you're using with it): 3.4.4
- Browser: Chrome
- OS: Linux

#### Did this work in previous versions?

Probably not, as I'm assume styled-jsx was designed for `className=`.

**Comment by huozhi** [comment]
Currently the babel plugin doesn't handle `class` property since it's for react specific.
