### ISSUE TITLE
`css.resolve` variable not working when imported from a external `.ts` file

### ISSUE THREAD

**Issue by thomasryu** [vercel/styled-jsx#780]
#### What is the current behavior?

Attempting to use a `css.resolve` variable imported from an external `.ts` results in the following error:
```
 ./Container/styles.ts
Module parse failed: Unexpected token (3:12)
File was processed with these loaders:
 * ./node_modules/next/dist/compiled/@next/react-refresh-utils/loader.js
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
| import _JSXStyle from "styled-jsx/style";
| export default {
>     styles: <_JSXStyle id={"71f03d42ea0ec6"}>{".container.jsx-71f03d42ea0ec6{background:#000;\ncolor:white;\nfont-weight:700;\nheight:100px}"}</_JSXStyle>,
|     className: "jsx-71f03d42ea0ec6"
| };
```

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Create a brand new Next.js + TypeScript project using `yarn create next-app --typescript`
and add the following files:

styles.ts
```
import css from 'styled-jsx/css'

export default css.resolve`
  .container {
    background: #000;
    color: white;
    font-weight: 700;
    height: 100px;
  }
`
```

Container.tsx
```
import container from './styles'

const Container: React.FC = (props) => {
  const {className, styles} = container
  return (
    <>
      <div className={`container ${className}`}>
        {props.children}
      </div>
      {styles}
    </>
  )
}
export default Container
```

And use the `<Container>` component anywhere.

#### What is the expected behavior?
The component and styles load properly.

#### Environment (include versions)

- Version of styled-jsx (or next.js if it's being used): next.js 12.0.9
- Browser: Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)
- OS: Ubuntu 20.04.2 LTS (fossa-kakuna X63)

**Comment by padmaia** [comment]
This is an issue because `css.resolve` generates jsx syntax, but because the filename is `.ts`, we aren't running the jsx transform. You can fix this issue by renaming the file with `css.resolve` to `.tsx`. We will work on adding a better error message though.

**Comment by thomasryu** [comment]
thank you very much!
