### ISSUE TITLE
Hook injection breaks animated styled on Styled JSX 5.0

### ISSUE THREAD

**Issue by vpontis** [vercel/styled-jsx#783]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug. This is actually the same bug as in #752. 

The behavior is fixed and works well in `styled-jsx@v5.0.0-beta.3` but then is broken in `styled-jsx@5.0.0`. So some commit between those two broke the style injection. 

#### What is the current behavior?

You can see the difference in behavior here:

- bad — https://luma-8jxscr6jr.luma-dev.com/aloha
- good — https://lu.ma/aloha

You can also see a minimal repro here: https://github.com/luma-team/styled-jsx-issue

#### Environment (include versions)

- Version of styled-jsx (or next.js if it's being used): 5.0.0 vs v5.0.0-beta.3
- Browser: Chrome
- OS: MacOS
- React — 18rc

#### Did this work in previous versions?

Yes

cc @huozhi who helped with this last time :)

**Comment by huozhi** [comment]
Seems you're using react 17 in the repro, can you try to bump react version to latest react 18 rc version? Since it requires new provided hook from react 18.

**Comment by vpontis** [comment]
Hi @huozhi, thanks for catching that. I have updated to React 18 in the repro and the error persists. (The two lu.ma examples linked above both use React 18.)

**Comment by huozhi** [comment]
I cannot test the demo due to the sass errors:
![image](https://user-images.githubusercontent.com/4800338/153867176-47d9cdf5-3613-477a-b4e8-9901dca820a3.png)

Without importing that file everything works fine. Could you help provide a runnable example like codesandbox that would be easy to repro it?

**Comment by vpontis** [comment]
Hmm those are just warnings. They shouldn't prevent you from running it. I'll see what I can do when on my computer later today.

**Comment by vpontis** [comment]
@huozhi I upgraded both Next and Styled-JSX together in a different project and it appears the error may be gone! I'll do some more testing and re-open this if I can reproduce the issue reliably. Thanks for all of your help!

**Comment by huozhi** [comment]
That's great to hear!
