### ISSUE TITLE
document is not defined in nextjs build

### ISSUE THREAD

**Issue by abbasEbadian** [vercel/styled-jsx#785]
#### Do you want to request a _feature_ or report a _bug_? report a _bug_
In next build,
I get `document is not defined` for all of my pages which caused by one single line.
As shown below:

![Screenshot_209](https://user-images.githubusercontent.com/16752051/155384141-5c0442fa-0115-4041-a48b-544a123f9b0e.png)

`
ReferenceError: document is not defined
    at new StyleSheet (H:\Projects\jiring\node_modules\styled-jsx\dist\index\index.js:136:35)  `

When i check document or window to be not `undefined`,  problem gets solved, like so:

`node_modules/styled-jsx/dist/index/index.js : 136`

From:
`    var node = this._isBrowser && document.querySelector('meta[property="csp-nonce"]');
`
To:
`    var node = this._isBrowser && (typeof document !== "undefined") && document.querySelector('meta[property="csp-nonce"]');
`

I thought problem is clear and adding this simple condition to the source, wont hurt others parts.
Please don't reject this topic because of  not providing some information, 
I'm in lack of time.
Hope it gets fixed soon.

styled-jsx ==5.0.0
next==12.1.0
react==17.0.2

**Comment by CheaterScript** [comment]
I have same issue, hot to fix it?

**Comment by abbasEbadian** [comment]
It seems there is a problem when using [SGR](https://nextjs.org/docs/basic-features/pages#static-generation-recommended) .
So i tried to use [SSR](https://nextjs.org/docs/basic-features/pages#server-side-rendering) instead.
Added these lines to end of my pages.
```
export async function getServerSideProps() {
    return { props: {  } }
}
```
just before the  `export  default AppName` line.

Additionally there were problem (`document not found` ) even with error pages, so created `pages/_error.js` with following content and added same snippet again:

```
function Error({ statusCode }) {
  return (
    <p>
      {statusCode
        ? `An error ${statusCode} occurred on server`
        : 'An error occurred on client'}
    </p>
  )
}

export async function getServerSideProps({}) {
  return {
    props: {  },
  }
}

export default Error
```
And now it works.

**Comment by CheaterScript** [comment]
Thanks.
I just move component from /pages to root,then it solved.

**Comment by huozhi** [comment]
Hi @abbasEbadian can you provide a minimal reproduction for us to investigate? I'm having trouble reproducing it
