### ISSUE TITLE
FOUC with latest styled-jsx and next

### ISSUE THREAD

**Issue by buesing** [vercel/styled-jsx#792]
#### Do you want to request a _feature_ or report a _bug_?
This is a bug. I realize there are a two FOUC issues already open but I believe this is something else, as it also happens even without a custom _document.js and in dev mode.

#### What is the current behavior?

Pages show a FOUC and show no styles at all when loaded without JS.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

See this vercel app: https://styled-jsx-fouc-repro.vercel.app/
And this repo for reproduction: https://github.com/buesing/styled-jsx-fouc-repro
To build locally simply do
```
npm run build
npm run start
```

#### What is the expected behavior?

Styles should show even without JS

#### Environment (include versions)

- Version of styled-jsx: 5.0.2
- Next: 12.1.4
- Browser: Chrome v100 but happens in every browser
- OS: MacOS 12

#### Did this work in previous versions?

Yes, but I'm not sure yet when exactly the bug was introduced.

**Comment by buesing** [comment]
Ran some more tests, there seems to be a weird correlation going on with next, where either updating next OR styled-jsx breaks SSR:

styled-jsx@4.0.1,  next@11.1.4: works
styled-jsx@4.0.1, next@12.1.5: broken
styled-jsx@5.0.0, next@12.1.0: works
styled-jsx@5.0.1, next@12.1.0: broken
styled-jsx@5.0.2, next@11.1.4: broken
styled-jsx@5.0.2, next@12.1.0: broken
styled-jsx@5.0.2, next@12.1.5 (latest of both): broken

I can't really make any sense from this, maybe my method is broken, or someone else has an idea of what's going on here?

**Comment by huozhi** [comment]
@buesing You shouldn't install styled-jsx into your project since it's already a dependency of next.js, that way will lead to duplicated styled-jsx instance inside next.js.

please try the follow steps
```
npm un -S styled-jsx
rm -rf node_modules package-lock.json
npm i
```

It works for me

**Comment by buesing** [comment]
Oh, ok wasn't aware of that. Works, thanks!
