### ISSUE TITLE
Make <reference types="styled-jsx" /> include global.d.ts?

### ISSUE THREAD

**Issue by jchnxu** [vercel/styled-jsx#825]
We cannot do `<reference types="styled-jsx/global" />`. And `import 'styled-jsx/global';` does not work either.

<img width="1637" alt="image" src="https://user-images.githubusercontent.com/4531670/212476389-5c2b90b2-e53a-40af-9022-4021d3534e2f.png">

I believe it's a huge pain point for people to use styled-jsx smoothly.
https://github.com/vercel/styled-jsx/issues/90

We have to write a duplicated global.d.ts for the typescript code to work. Next.js do it this way. It does not make sense for people to do it every time they want to use it.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/4531670/212476526-db16fd06-4d6b-4130-be1c-4728c836462d.png">

**Comment by jchnxu** [comment]
I managed to make it work using `import type from 'styled-jsx/global'`. Wouldn't it be nice that we document it? 

Or could we explicitly export `<reference types="styled-jsx/global" />`?

**Comment by adarshaacharya** [comment]
@addlistener using Next 13.x and still facing same issue, For now created `custom.d.ts` in `src/` and pasted given code it works now

```
import 'react';

declare module 'react' {
  interface StyleHTMLAttributes<T> extends React.HTMLAttributes<T> {
    jsx?: boolean;
    global?: boolean;
  }
}
```


Are there any better option than that?

**Comment by addlistener** [comment]
@adarshaacharya 

Have you tried the following? 

1. checking your styled-jsx version?
2. `import type from 'styled-jsx/global'`
3. `<reference types="styled-jsx/global" />`
