### ISSUE TITLE
Support for vite + swc

### ISSUE THREAD

**Issue by liliwei25** [vercel/styled-jsx#834]
#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

i tried to setup my vite config like below but i am getting an error
```typescript
import react from '@vitejs/plugin-react-swc'
import { defineConfig } from 'vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react({ plugins: [["@swc/plugin-styled-jsx", {}]]})],
  server: {
    port: 3000,
  },
})
```
<img width="1660" alt="Screenshot 2023-05-29 at 1 03 01 AM" src="https://github.com/vercel/styled-jsx/assets/22389228/b8d13c98-dc9f-4738-b1c2-b27d7daa2511">

#### Environment (include versions)

- Version of styled-jsx (or next.js if it's being used): 5.1.2
- Browser: Chrome
- OS: Mac

**Comment by huozhi** [comment]
Close as this is the issue to https://github.com/swc-project/plugins where the swc plugin is maintained
